/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import dao.daoCuenta;
import dao.daoPartida;
import entity.Cuentas;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Rafaelano
 */
public class Mayor extends javax.swing.JPanel {

    private daoCuenta cDAO = new daoCuenta();
    daoPartida pDAO = new daoPartida();
    Cuentas cuenta = new Cuentas();
    DefaultTableModel model;

    /**
     * Creates new form Mayor
     */
    public Mayor() {
        initComponents();
        DefaultTableModel model;
        String[] titulo = {"Nº Partida", "Fecha", "Cuenta", "Descripcion", "Debe", "Haber"};
        model = new DefaultTableModel(null, titulo);
        tblMayor.setModel(model);
        getCuentas(cmbCuenta);
        ocultar();
    }

    /**
     * METODOS
     *
     */
    private void getCuentas(JComboBox cmb) {
        cDAO.getCuentaCmb(cmb);
    }

    //Traer la consulta de cuentas
    private void getDetalleCuenta() {
        cuenta = (Cuentas) cmbCuenta.getSelectedItem();
        int codCuenta = this.cuenta.getCodCuenta();
        pDAO.listarMayor(tblMayor, codCuenta);
        int saldo = this.cuenta.getIdSaldo().getIdSaldo();
        if (tblMayor.getRowCount() > 0) {
            saldarCuentas(saldo);
        }else{
            ocultar();
        }

    }

    //para saldar las cuentas
    private void saldarCuentas(int saldo) {
        double sum1 = 0;
        double sum2 = 0;
        double a, b;
        double sa;
        if (tblMayor.getRowCount() > 0) {
            for (int i = 0; i < tblMayor.getRowCount(); i++) {
                a = (double) Double.parseDouble(tblMayor.getValueAt(i, 4).toString());
                b = (double) Double.parseDouble(tblMayor.getValueAt(i, 5).toString());
                sum2 += b;
                sum1 += a;

            }
            txtHaber.setText("$ " + sum2);
            txtDebe.setText("$ " + sum1);
            if (saldo == 1) {
                sa = sum1 - sum2;
                txtAc.setText("$ " + sa);
                txtDeu.setText("");
            } else {
                sa = sum2 - sum1;
                txtAc.setText("");
                txtDeu.setText("$ " + sa);
            }
            mostrar();

        }
    }

    //para ocultar y mostrar elementos
    private void ocultar() {
        txtAc.setVisible(false);
        txtDeu.setVisible(false);
        txtDebe.setVisible(false);
        txtHaber.setVisible(false);
        txtSaldo.setVisible(false);
        txtSuma.setVisible(false);
        jSeparator1.setVisible(false);
    }

    private void mostrar() {
        txtAc.setVisible(true);
        txtDeu.setVisible(true);
        txtDebe.setVisible(true);
        txtHaber.setVisible(true);
        txtSaldo.setVisible(true);
        txtSuma.setVisible(true);
        jSeparator1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMayor = new javax.swing.JTable();
        btnGenerar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cmbCuenta = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        txtHaber = new javax.swing.JLabel();
        txtAc = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtDebe = new javax.swing.JLabel();
        txtDeu = new javax.swing.JLabel();
        txtSuma = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(780, 510));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Libro Mayor");

        jPanel2.setBackground(new java.awt.Color(246, 246, 246));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMayor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblMayor);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 690, 230));

        btnGenerar.setBackground(new java.awt.Color(0, 102, 255));
        btnGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGenerarMousePressed(evt);
            }
        });
        btnGenerar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Generar Reporte");
        btnGenerar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 110, 30));

        cmbCuenta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jPanel2.add(cmbCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 280, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setText("Cuenta");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        txtSaldo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtSaldo.setText("Saldo");
        jPanel2.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        txtHaber.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtHaber.setText("Haber");
        jPanel2.add(txtHaber, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, -1, -1));

        txtAc.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtAc.setText("SaldoAc");
        jPanel2.add(txtAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 200, 10));

        txtDebe.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtDebe.setText("Debe");
        jPanel2.add(txtDebe, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        txtDeu.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtDeu.setText("SaldoDe");
        jPanel2.add(txtDeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, -1, -1));

        txtSuma.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtSuma.setText("Sumas");
        jPanel2.add(txtSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMousePressed
        getDetalleCuenta();
    }//GEN-LAST:event_btnGenerarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnGenerar;
    private javax.swing.JComboBox<Cuentas> cmbCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblMayor;
    private javax.swing.JLabel txtAc;
    private javax.swing.JLabel txtDebe;
    private javax.swing.JLabel txtDeu;
    private javax.swing.JLabel txtHaber;
    private javax.swing.JLabel txtSaldo;
    private javax.swing.JLabel txtSuma;
    // End of variables declaration//GEN-END:variables
}
