/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JPanel;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author Carlos Rafaelano
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setTitle("Sistema Contable");
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        //para escribir la fecha en la pantalla
        LocalDate now = LocalDate.now();
        int year = now.getYear();
        int dia = now.getDayOfMonth();
        int month = now.getMonthValue();
        String[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", " ;Septiembre",
            "Octubre", "Noviembre", "Diciemrbre"};
        fecha.setText("Hoy es " + dia + " de " + meses[month - 1] + " de " + year);
        //para mostrar el Dashboard
        Dashboard ds = new Dashboard();
        ds.setSize(780, 510);
        ds.setLocation(0, 0);
        content.removeAll();
        content.add(ds, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        barra = new javax.swing.JPanel();
        textBarra = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        textHeader = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        btnPrincipal1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnRegsitro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnLibroDiario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnLibroMayor = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnComprobación = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGeneral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnEmpleado = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnPlanilla = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setBackground(new java.awt.Color(0, 0, 0));
        barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textBarra.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        textBarra.setForeground(new java.awt.Color(255, 255, 255));
        textBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBarra.setText("Sistema de Registro Contable");
        barra.add(textBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1090, 40));

        background.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 40));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngegg.png"))); // NOI18N

        textHeader.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        textHeader.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textHeader.setText("Hola bienvenido al sistema de registro contable");

        fecha.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(textHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 780, 120));

        menu.setBackground(new java.awt.Color(51, 51, 51));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrincipal1.setBackground(new java.awt.Color(45, 45, 45));
        btnPrincipal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrincipal1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrincipal1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrincipal1MousePressed(evt);
            }
        });
        btnPrincipal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Principal");
        btnPrincipal1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        menu.add(btnPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 310, 60));

        btnRegsitro.setBackground(new java.awt.Color(62, 62, 62));
        btnRegsitro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegsitroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegsitroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRegsitroMousePressed(evt);
            }
        });
        btnRegsitro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registrar Movimientos");
        btnRegsitro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        menu.add(btnRegsitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 310, 60));

        btnLibroDiario.setBackground(new java.awt.Color(62, 62, 62));
        btnLibroDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibroDiarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibroDiarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLibroDiarioMousePressed(evt);
            }
        });
        btnLibroDiario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Libro Diario");
        btnLibroDiario.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        menu.add(btnLibroDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 310, 60));

        btnLibroMayor.setBackground(new java.awt.Color(62, 62, 62));
        btnLibroMayor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibroMayorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibroMayorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLibroMayorMousePressed(evt);
            }
        });
        btnLibroMayor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Libro Mayor");
        btnLibroMayor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        menu.add(btnLibroMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 310, 60));

        btnComprobación.setBackground(new java.awt.Color(62, 62, 62));
        btnComprobación.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprobaciónMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprobaciónMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnComprobaciónMousePressed(evt);
            }
        });
        btnComprobación.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Balance de Comprobación");
        btnComprobación.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        menu.add(btnComprobación, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 310, 60));

        btnGeneral.setBackground(new java.awt.Color(62, 62, 62));
        btnGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGeneralMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGeneralMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGeneralMousePressed(evt);
            }
        });
        btnGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Balance General");
        btnGeneral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        menu.add(btnGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 310, 60));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Menú");
        menu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 80, 30));
        menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 170, 10));

        btnEmpleado.setBackground(new java.awt.Color(62, 62, 62));
        btnEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmpleadoMousePressed(evt);
            }
        });
        btnEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingresar Empleado");
        btnEmpleado.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        menu.add(btnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 310, 60));

        btnPlanilla.setBackground(new java.awt.Color(62, 62, 62));
        btnPlanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlanillaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlanillaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlanillaMousePressed(evt);
            }
        });
        btnPlanilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Planilla");
        btnPlanilla.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        menu.add(btnPlanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 310, 60));

        background.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 310, 630));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setMinimumSize(new java.awt.Dimension(780, 510));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 780, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrincipal1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipal1MouseEntered
        if (btnPrincipal1.getBackground().getRGB() == -12698050)
            setColor(btnPrincipal1);
    }//GEN-LAST:event_btnPrincipal1MouseEntered

    private void btnPrincipal1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipal1MouseExited
        if (btnComprobación.getBackground().getRGB() != -12698050 || btnGeneral.getBackground().getRGB() != -12698050 || btnRegsitro.getBackground().getRGB() != -12698050
                || btnLibroDiario.getBackground().getRGB() != -12698050 || btnLibroMayor.getBackground().getRGB() != -12698050 || btnEmpleado.getBackground().getRGB() != -12698050 || btnPlanilla.getBackground().getRGB() != -12698050)
            resetColor(btnPrincipal1);
    }//GEN-LAST:event_btnPrincipal1MouseExited

    private void btnRegsitroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegsitroMouseEntered
        if (btnRegsitro.getBackground().getRGB() == -12698050)
            setColor(btnRegsitro);
    }//GEN-LAST:event_btnRegsitroMouseEntered

    private void btnRegsitroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegsitroMouseExited
        if (btnComprobación.getBackground().getRGB() != -12698050 || btnGeneral.getBackground().getRGB() != -12698050 || btnPrincipal1.getBackground().getRGB() != -12698050
                || btnLibroDiario.getBackground().getRGB() != -12698050 || btnLibroMayor.getBackground().getRGB() != -12698050 || btnEmpleado.getBackground().getRGB() != -12698050 || btnPlanilla.getBackground().getRGB() != -12698050)
            resetColor(btnRegsitro);
    }//GEN-LAST:event_btnRegsitroMouseExited

    private void btnLibroDiarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroDiarioMouseEntered
        if (btnLibroDiario.getBackground().getRGB() == -12698050)
            setColor(btnLibroDiario);
    }//GEN-LAST:event_btnLibroDiarioMouseEntered

    private void btnLibroDiarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroDiarioMouseExited
        if (btnComprobación.getBackground().getRGB() != -12698050 || btnGeneral.getBackground().getRGB() != -12698050 || btnRegsitro.getBackground().getRGB() != -12698050
                || btnPrincipal1.getBackground().getRGB() != -12698050 || btnLibroMayor.getBackground().getRGB() != -12698050 || btnEmpleado.getBackground().getRGB() != -12698050 || btnPlanilla.getBackground().getRGB() != -12698050)
            resetColor(btnLibroDiario);
    }//GEN-LAST:event_btnLibroDiarioMouseExited

    private void btnLibroMayorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroMayorMouseEntered
        if (btnLibroMayor.getBackground().getRGB() == -12698050)
            setColor(btnLibroMayor);
    }//GEN-LAST:event_btnLibroMayorMouseEntered

    private void btnLibroMayorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroMayorMouseExited
        if (btnComprobación.getBackground().getRGB() != -12698050 || btnGeneral.getBackground().getRGB() != -12698050 || btnRegsitro.getBackground().getRGB() != -12698050
                || btnLibroDiario.getBackground().getRGB() != -12698050 || btnPrincipal1.getBackground().getRGB() != -12698050 || btnEmpleado.getBackground().getRGB() != -12698050 || btnPlanilla.getBackground().getRGB() != -12698050)
            resetColor(btnLibroMayor);
    }//GEN-LAST:event_btnLibroMayorMouseExited

    private void btnComprobaciónMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprobaciónMouseEntered
        if (btnComprobación.getBackground().getRGB() == -12698050)
            setColor(btnComprobación);
    }//GEN-LAST:event_btnComprobaciónMouseEntered

    private void btnComprobaciónMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprobaciónMouseExited
        if (btnPrincipal1.getBackground().getRGB() != -12698050 || btnGeneral.getBackground().getRGB() != -12698050 || btnRegsitro.getBackground().getRGB() != -12698050
                || btnLibroDiario.getBackground().getRGB() != -12698050 || btnLibroMayor.getBackground().getRGB() != -12698050 || btnEmpleado.getBackground().getRGB() != -12698050 || btnPlanilla.getBackground().getRGB() != -12698050)
            resetColor(btnComprobación);
    }//GEN-LAST:event_btnComprobaciónMouseExited

    private void btnGeneralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeneralMouseEntered
        if (btnGeneral.getBackground().getRGB() == -12698050)
            setColor(btnGeneral);
    }//GEN-LAST:event_btnGeneralMouseEntered

    private void btnGeneralMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeneralMouseExited
        if (btnComprobación.getBackground().getRGB() != -12698050 || btnPrincipal1.getBackground().getRGB() != -12698050 || btnRegsitro.getBackground().getRGB() != -12698050
                || btnLibroDiario.getBackground().getRGB() != -12698050 || btnLibroMayor.getBackground().getRGB() != -12698050 || btnEmpleado.getBackground().getRGB() != -12698050 || btnPlanilla.getBackground().getRGB() != -12698050)
            resetColor(btnGeneral);
    }//GEN-LAST:event_btnGeneralMouseExited

    private void btnRegsitroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegsitroMousePressed
        setColor(btnRegsitro);
        resetColor(btnPrincipal1);
        resetColor(btnComprobación);
        resetColor(btnGeneral);
        resetColor(btnLibroMayor);
        resetColor(btnLibroDiario);
        resetColor(btnEmpleado);
        resetColor(btnPlanilla);
        //Abrir vista
        Registro vs = new Registro();
        vs.setSize(780, 510);
        vs.setLocation(0, 0);
        content.removeAll();
        content.add(vs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnRegsitroMousePressed

    private void btnPrincipal1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipal1MousePressed
        setColor(btnPrincipal1);
        resetColor(btnRegsitro);
        resetColor(btnComprobación);
        resetColor(btnGeneral);
        resetColor(btnLibroMayor);
        resetColor(btnLibroDiario);
        resetColor(btnEmpleado);
        resetColor(btnPlanilla);
        //Abrir vista
        Dashboard vs = new Dashboard();
        vs.setSize(780, 510);
        vs.setLocation(0, 0);
        content.removeAll();
        content.add(vs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnPrincipal1MousePressed

    private void btnLibroDiarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroDiarioMousePressed
        setColor(btnLibroDiario);
        resetColor(btnRegsitro);
        resetColor(btnComprobación);
        resetColor(btnGeneral);
        resetColor(btnLibroMayor);
        resetColor(btnPrincipal1);
        resetColor(btnEmpleado);
        resetColor(btnPlanilla);
        //Abrir vista
        Diario vs = new Diario();
        vs.setSize(780, 510);
        vs.setLocation(0, 0);
        content.removeAll();
        content.add(vs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnLibroDiarioMousePressed

    private void btnLibroMayorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibroMayorMousePressed
        setColor(btnLibroMayor);
        resetColor(btnRegsitro);
        resetColor(btnComprobación);
        resetColor(btnGeneral);
        resetColor(btnLibroDiario);
        resetColor(btnPrincipal1);
        resetColor(btnEmpleado);
        resetColor(btnPlanilla);
        //Abrir vista
        Mayor vs = new Mayor();
        vs.setSize(780, 510);
        vs.setLocation(0, 0);
        content.removeAll();
        content.add(vs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnLibroMayorMousePressed

    private void btnComprobaciónMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprobaciónMousePressed
        setColor(btnComprobación);
        resetColor(btnRegsitro);
        resetColor(btnLibroDiario);
        resetColor(btnGeneral);
        resetColor(btnLibroMayor);
        resetColor(btnPrincipal1);
        resetColor(btnEmpleado);
        resetColor(btnPlanilla);
        //Abrir vista
        BComprobacion vs = new BComprobacion();
        vs.setSize(780, 510);
        vs.setLocation(0, 0);
        content.removeAll();
        content.add(vs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnComprobaciónMousePressed

    private void btnGeneralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeneralMousePressed
        setColor(btnGeneral);
        resetColor(btnRegsitro);
        resetColor(btnComprobación);
        resetColor(btnLibroDiario);
        resetColor(btnLibroMayor);
        resetColor(btnPrincipal1);
        resetColor(btnEmpleado);
        resetColor(btnPlanilla);
        //Abrir vista
        BGeneral vs = new BGeneral();
        vs.setSize(780, 510);
        vs.setLocation(0, 0);
        content.removeAll();
        content.add(vs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnGeneralMousePressed

    private void btnEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseEntered
        if (btnEmpleado.getBackground().getRGB() == -12698050)
            setColor(btnEmpleado);
    }//GEN-LAST:event_btnEmpleadoMouseEntered

    private void btnEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseExited
        if (btnComprobación.getBackground().getRGB() != -12698050 || btnGeneral.getBackground().getRGB() != -12698050 || btnRegsitro.getBackground().getRGB() != -12698050
                || btnLibroDiario.getBackground().getRGB() != -12698050 || btnLibroMayor.getBackground().getRGB() != -12698050 || btnPrincipal1.getBackground().getRGB() != -12698050 || btnPlanilla.getBackground().getRGB() != -12698050)
            resetColor(btnEmpleado);
    }//GEN-LAST:event_btnEmpleadoMouseExited

    private void btnEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMousePressed
        setColor(btnEmpleado);
        resetColor(btnGeneral);
        resetColor(btnRegsitro);
        resetColor(btnComprobación);
        resetColor(btnLibroDiario);
        resetColor(btnLibroMayor);
        resetColor(btnPrincipal1);
        resetColor(btnPlanilla);
        //Abrir vista
        ElementosDeCostos vs = new ElementosDeCostos();
        vs.setSize(780, 510);
        vs.setLocation(0, 0);
        content.removeAll();
        content.add(vs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnEmpleadoMousePressed

    private void btnPlanillaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanillaMouseEntered
        if (btnPlanilla.getBackground().getRGB() == -12698050)
            setColor(btnPlanilla);
    }//GEN-LAST:event_btnPlanillaMouseEntered

    private void btnPlanillaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanillaMouseExited
        if (btnComprobación.getBackground().getRGB() != -12698050 || btnGeneral.getBackground().getRGB() != -12698050 || btnRegsitro.getBackground().getRGB() != -12698050
                || btnLibroDiario.getBackground().getRGB() != -12698050 || btnLibroMayor.getBackground().getRGB() != -12698050 || btnPrincipal1.getBackground().getRGB() != -12698050 || btnEmpleado.getBackground().getRGB() != -12698050)
            resetColor(btnPlanilla);
    }//GEN-LAST:event_btnPlanillaMouseExited

    private void btnPlanillaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanillaMousePressed
        setColor(btnPlanilla);
        resetColor(btnGeneral);
        resetColor(btnRegsitro);
        resetColor(btnComprobación);
        resetColor(btnLibroDiario);
        resetColor(btnLibroMayor);
        resetColor(btnPrincipal1);
        resetColor(btnEmpleado);
        //Abrir vista
        Costos vs = new Costos();
        vs.setSize(780, 510);
        vs.setLocation(0, 0);
        content.removeAll();
        content.add(vs, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btnPlanillaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });

    }

    /*
        Metodos globales
     */
    void setColor(JPanel panel) {
        panel.setBackground(new Color(45, 45, 45));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(62, 62, 62));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel barra;
    private javax.swing.JPanel btnComprobación;
    private javax.swing.JPanel btnEmpleado;
    private javax.swing.JPanel btnGeneral;
    private javax.swing.JPanel btnLibroDiario;
    private javax.swing.JPanel btnLibroMayor;
    private javax.swing.JPanel btnPlanilla;
    private javax.swing.JPanel btnPrincipal1;
    private javax.swing.JPanel btnRegsitro;
    private javax.swing.JPanel content;
    private javax.swing.JLabel fecha;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel textBarra;
    private javax.swing.JLabel textHeader;
    // End of variables declaration//GEN-END:variables
}
